### ISSUE TITLE
Intial worker sync should be done via RabbitMQ & not via a direct connection to MongoDB

### ISSUE THREAD

**Issue by naorlivne** [nebula-orchestrator/worker-manager#29]
## Expected/Wanted Behavior
Upon starting a new worker it should request Via RabbitMQ the newest app config - this should be done via a queue where all the api-managers listens to and reply in a new thread.

## Actual Behavior
Currently upon starting a new worker it connects directly to MongoDB & get the current app config from it - this is not ideal as it requires a read only MongoDB connection from every worker reachable for the intial sync

**Comment by nochte** [comment]
Could instead have the worker hit an API endpoint for that config.

**Comment by naorlivne** [comment]
There are 2 reasons I think using RabbitMQ will be preferable over polling the API:

- Polling the API  requires having it accessible to all workers in addition to RabbitMQ, this adds complexity to setting up workers & security wise increases the possible attack surface (as the entire architecture of Nebula revolves around RabbitMQ removing that instead would be near impossible)
- Polling the API adds a risk of a "roaring horde" problem if\when a lot of workers attempt to do the initial sync at the same time, the current workaround of having a random delay before syncing will solve that with the API but as RabbitMQ can simply queue massages & reply to them in order it removes the need of that random delay which should help speed up the initial sync.

That been said I'm a strong believer in letting the end user choose how to configure his\hers tools and adding an optional envvar\config-setting which allows the workers to query via the API rather then through RabbitMQ won't  be that much of work (in fact there is already an API endpoint which returns the config of an app) so why not have both?

@nochte feel like raising a ticket request about it?

**Comment by naorlivne** [comment]
Attached is the planned worker "bootstraping" workflow for resolving this ticket via RabbitMQ direct reply RPC calls, after a lot of thoughts and discussions with multiple knowledgeable people this feels to me like the best course of action as it both allows the flexibility of AMQP will still remaining simple to implement in a scalable fashion.

![nebula_rabbitmq_direct_reply_worker_startup_sync](https://user-images.githubusercontent.com/5310609/43591113-3dcb2dd2-967b-11e8-916c-de834770414e.jpg)

**Comment by naorlivne** [comment]
Pushed to latest\master, will be added to next numbered release (which due to the major architectural change will be a Major release to v2.0.0).
